sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.20.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x /usr/local/bin/docker-compose

  - docker version

  - docker build --no-cache -t eloygc/alpine-php:7.2 -f 7.2/prod/Dockerfile 7.2/prod
  - docker build --no-cache -t eloygc/alpine-php:7.2-dev -f 7.2/dev/Dockerfile 7.2/dev

  - docker build --no-cache -t eloygc/alpine-php:7.1 -f 7.1/prod/Dockerfile 7.1/prod
  - docker build --no-cache -t eloygc/alpine-php:7.1-dev -f 7.1/dev/Dockerfile 7.1/dev

  - docker run --name php7.2 -d -v $PWD:/app eloygc/alpine-php:7.2
  - docker run --name php7.2-dev -d -v $PWD:/app eloygc/alpine-php:7.2-dev

  - docker run --name php7.1 -d -v $PWD:/app eloygc/alpine-php:7.1
  - docker run --name php7.1-dev -d -v $PWD:/app eloygc/alpine-php:7.1-dev

  - docker-compose -f test/docker-compose.yml up -d

script:
  - docker exec php7.2 php -v
  - docker exec php7.2 sh -c "php -v | grep OPcache"
  - docker exec php7.2 sh -c "php test/index.php | grep Demo"
  - docker exec php7.2 sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 512M"

  - docker exec php7.2-dev sh -c "php -v | grep Xdebug"
  - docker exec php7.2-dev composer --version
  - docker exec php7.2-dev sh -c "php test/index.php | grep Demo"
  - docker exec php7.2-dev sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 1G"

  - docker exec php7.1 php -v
  - docker exec php7.1 sh -c "php -v | grep OPcache"
  - docker exec php7.1 sh -c "php test/index.php | grep Demo"
  - docker exec php7.1 sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 512M"

  - docker exec php7.1-dev sh -c "php -v | grep Xdebug"
  - docker exec php7.1-dev composer --version
  - docker exec php7.1-dev sh -c "php test/index.php | grep Demo"
  - docker exec php7.1-dev sh -c "echo \"<?php echo ini_get('memory_limit');\" | php | grep 1G"

  - docker exec test_fpm_1 sh -c "curl -s nginx |grep Demo"